baseURL = "https://benoitlecallennec-hes.github.io/template_website_course/"
relativeURLs = false
languageCode = "fr"
title = "HE-Arc | 9999.9 Template de cours"
theme = "book"
enableGitInfo = true

[params]
BookSearch = true
BookRepo = "https://github.com/benoitlecallennec-hes/template_website_course"
debugSlides = true

[Taxonomies]
  tag = "tags"

[markup]
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "vs"

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

