baseURL = "https://he-arc.github.io/3292.2-Introduction_Unity/"
relativeURLs = false
languageCode = "fr"
title = "HE-Arc | 3292.2 Introduction Ã  Unity"
theme = "book"
enableGitInfo = true

[params]
BookSearch = true
BookRepo = "https://github.com/HE-Arc/3292.2-Introduction_Unity"
debugSlides = true

[Taxonomies]
  tag = "tags"

[markup]
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "vs"

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

